# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-e',
  'process.stdout.write(require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  ))', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RADIUSLTD' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # NFC
  pod 'react-native-nfc-manager', :path => '../node_modules/react-native-nfc-manager'

  # BLE
  pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'

  # AsyncStorage
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  # WebView
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  # Vector Icons
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'RADIUSLTDTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
